service: lambda-jbake-pipeline

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: java8
  stage: demo
  region: eu-central-1
  deploymentBucket: dasniko.serverless.deployments.${self:provider.region}
  environment:
    QUEUENAME: jbake-queue
    BUCKETNAME: dasniko-${self:service}

custom: ${file(sls-props.yml)}

package:
  artifact: target/lambda-jbake-pipeline.jar

functions:
  hook:
    handler: dasniko.serverless.jbake.GitHookHandler
    events:
      - http:
          path: hook
          method: post
    memorySize: 512
    timeout: 30
    iamRoleStatements:
      - Effect: Allow
        Action:
          - sqs:sendMessage
        Resource: "arn:aws:sqs:${self:provider.region}:${self:custom.accountId}:${self:provider.environment.QUEUENAME}"
  bake:
    handler: dasniko.serverless.jbake.BakeHandler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - JBakeQ
              - Arn
    memorySize: 1024
    timeout: 60
    iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:put
        Resource: "arn:aws:s3:::${self:provider.environment.BUCKETNAME}"

resources:
  Resources:
    JBakeQ:
      Type: AWS::SQS::Queue
      Properties:
        MessageRetentionPeriod: 60
        QueueName: ${self:provider.environment.QUEUENAME}
        VisibilityTimeout: 60
